CREATE DATABASE CoastalLife;
USE CoastalLife;

CREATE TABLE Document (
  id INT AUTO_INCREMENT PRIMARY KEY,
  propertyId TEXT NULL,
  address_houseNumber INT NULL,
  address_street TEXT NULL,
  address_city TEXT NULL,
  address_county TEXT NULL,
  address_countyFipsCode INT NULL,
  address_state TEXT NULL,
  address_zip INT NULL,
  address_zipPlus4 INT NULL,
  mls_appliances TEXT NULL,
  mls_architecturalStyle TEXT NULL,
  mls_bathroomCount INT NULL,
  mls_bedroomCount INT NULL,
  mls_buildingStyle TEXT NULL,
  mls_condoFloorNumber INT NULL,
  mls_coolingTypes TEXT NULL,
  mls_description TEXT NULL,
  mls_directions TEXT NULL,
  mls_exteriorConstruction TEXT NULL,
  mls_failedListingDate DATE NULL,
  mls_floorCount INT NULL,
  mls_fullBathroomCount INT NULL,
  mls_halfBathroomCount INT NULL,
  mls_hasCeilingFan ENUM("TRUE", "FALSE") NULL,
  mls_hasFireplace ENUM("TRUE", "FALSE") NULL,
  mls_hasVaultedCeiling ENUM("TRUE", "FALSE") NULL,
  mls_heatingFuelTypes TEXT NULL,
  mls_heatingTypes TEXT NULL,
  mls_initialListingStatus TEXT NULL,
  mls_latitude DECIMAL(10, 6) NULL,
  mls_listingCategory TEXT NULL,
  mls_listingKey TEXT NULL,
  mls_livingArea INT NULL,
  mls_longitude DECIMAL(10, 6) NULL,
  mls_lotSizeSquareFeet DECIMAL NULL,
  mls_maxListPrice INT NULL,
  mls_maxListPriceDate DATE NULL,
  mls_minListPrice INT NULL,
  mls_minListPriceDate DATE NULL,
  mls_mlsId TEXT NULL,
  mls_mlsName TEXT NULL,
  mls_mlsNumber INT NULL,
  mls_neighborhood TEXT NULL,
  mls_newConstruction ENUM("TRUE", "FALSE") NULL,
  mls_oneQuarterBathroomCount INT NULL,
  mls_originalListingDate DATE NULL,
  mls_parkingSpaceCount INT NULL,
  mls_partialBathroomCount INT NULL,
  mls_patio TEXT NULL,
  mls_price INT NULL,
  mls_daysOnMarket INT NULL,
  mls_propertySubtype TEXT NULL,
  mls_propertyType TEXT NULL,
  mls_rentalIndicator TEXT NULL,
  mls_rental TEXT (255) NULL,
  mls_roofTypes TEXT NULL,
  mls_soldDate DATE NULL,
  mls_soldPrice INT NULL,
  mls_status ENUM("Pending", "Sold", "Active") NULL,
  mls_statusSubtype ENUM("Under Agreement", "Closed", "Active", "Coming Soon") NULL,
  mls_subDivision TEXT NULL,
  mls_title TEXT NULL,
  mls_totalBuildingAreaSquareFeet INT NULL,
  mls_yearBuilt INT NULL,
  mls_salePriceIsEstimated ENUM("TRUE", "FALSE") NULL,
  mls_realtorId TEXT NULL,
  mls_copyright TEXT NULL,
  mls_disclaimer TEXT NULL,
  mls_agentOffices_officeAddress_1 TEXT NULL,
  mls_agentOffices_officeAddress_2 TEXT NULL,
  mls_agentOffices_officeEmail_1 VARCHAR(200) NULL,
  mls_agentOffices_officeEmail_2 VARCHAR(200) NULL,
  mls_agentOffices_officeCorporateName_1 VARCHAR(200) NULL,
  mls_agentOffices_officeCorporateName_2 VARCHAR(200) NULL,
  mls_agentOffices_officePhoneNumber_1 VARCHAR(200) NULL,
  mls_agentOffices_officePhoneNumber_2 VARCHAR(200) NULL,
  mls_agentOffices_key_1 VARCHAR(200) NULL,
  mls_agentOffices_key_2 VARCHAR(200) NULL,
  mls_agentOffices_name_1  VARCHAR(200) NULL,
  mls_agentOffices_name_2  VARCHAR(200) NULL,
  mls_agentOffices_agentId_1 TEXT NULL,
  mls_agentOffices_agentId_2 TEXT NULL,
  mls_agentOffices_mainOfficeId_1 TEXT NULL,
  mls_agentOffices_mainOfficeId_2 TEXT NULL,
  mls_agentOffices_agentCodeId_1 TEXT NULL,
  mls_agentOffices_agentCodeId_2 TEXT NULL,
  mls_agentOffices_websiteUrl_1 TEXT NULL,
  mls_agentOffices_websiteUrl_2 TEXT NULL,
  mls_agentOffices_phoneNumber_1 VARCHAR(200) NULL,
  mls_agentOffices_phoneNumber_2 VARCHAR(200) NULL,
  mls_agentOffices_fax_1 VARCHAR(200) NULL,
  mls_agentOffices_fax_2 VARCHAR(200) NULL,
  mls_brokerage_address TEXT NULL,
  mls_brokerage_email VARCHAR(200) NULL,
  mls_brokerage_name VARCHAR(200) NULL,
  mls_brokerage_phoneNumber VARCHAR(200) NULL,
  mls_brokerage_websiteUrl VARCHAR(200) NULL,
  mls_agents_licenseNumber_1 INT NULL,
  mls_agents_licenseNumber_2 INT NULL,
  mls_agents_licenseNumber_3 INT NULL,
  mls_agents_licenseNumber_4 INT NULL,
  mls_agents_name_1 TEXT NULL,
  mls_agents_name_2 TEXT NULL,
  mls_agents_name_3 TEXT NULL,
  mls_agents_name_4 TEXT NULL,
  mls_agents_key_1 TEXT NULL,
  mls_agents_key_2 TEXT NULL,
  mls_agents_key_3 TEXT NULL,
  mls_agents_key_4 TEXT NULL,
  mls_agents_role_1 TEXT NULL,
  mls_agents_role_2 TEXT NULL,
  mls_agents_role_3 TEXT NULL,
  mls_agents_role_4 TEXT NULL,
  mls_agents_primaryPhoneNumber_1 VARCHAR(200) NULL,
  mls_agents_primaryPhoneNumber_2 VARCHAR(200) NULL,
  mls_agents_primaryPhoneNumber_3 VARCHAR(200) NULL,
  mls_agents_primaryPhoneNumber_4 VARCHAR(200) NULL,
  mls_agents_officePhoneNumber_1 VARCHAR(200) NULL,
  mls_agents_officePhoneNumber_2 VARCHAR(200) NULL,
  mls_agents_officePhoneNumber_3 VARCHAR(200) NULL,
  mls_agents_officePhoneNumber_4 VARCHAR(200) NULL,
  mls_agents_websiteUrl_1 VARCHAR(200) NULL,
  mls_agents_websiteUrl_2 VARCHAR(200) NULL,
  mls_agents_websiteUrl_3 VARCHAR(200) NULL,
  mls_agents_websiteUrl_4 VARCHAR(200) NULL,
  mls_agents_email_1 VARCHAR(200) NULL,
  mls_agents_email_2 VARCHAR(200) NULL,
  mls_agents_email_3 VARCHAR(200) NULL,
  mls_agents_email_4 VARCHAR(200) NULL,
  mls_schools_name_1 VARCHAR(200) NULL,
  mls_schools_name_2 VARCHAR(200) NULL,
  mls_schools_name_3 VARCHAR(200) NULL,
  mls_schools_name_4 VARCHAR(200) NULL,
  mls_schools_category_1 VARCHAR(200) NULL,
  mls_schools_category_2 VARCHAR(200) NULL,
  mls_schools_category_3 VARCHAR(200) NULL,
  mls_schools_category_4 VARCHAR(200) NULL,
  mls_schools_district_1 VARCHAR(200) NULL,
  mls_schools_district_2 VARCHAR(200) NULL,
  mls_schools_district_3 VARCHAR(200) NULL,
  mls_schools_district_4 VARCHAR(200) NULL,
  mls_taxes_year_1  INT NULL,
  mls_taxes_year_2  INT NULL,
  mls_taxes_amount_1 INT NULL,
  mls_taxes_amount_2 INT NULL,
  mls_taxes_description_1 VARCHAR(200) NULL,
  mls_taxes_description_2 VARCHAR(200) NULL,
  PREVIOUS_MLS_STATUS ENUM("Pending", "Sold", "Active", "Cancel") NULL,
  entryDate DATE NULL
);


CREATE INDEX idx_address_state ON Document (address_state(255));
CREATE INDEX idx_mls_propertyType ON Document (mls_propertyType(255));
CREATE INDEX idx_mls_propertySubtype ON Document (mls_propertySubtype(255));
CREATE INDEX idx_address_zip ON Document (address_zip);
CREATE INDEX idx_address_county ON Document (address_county(255));
CREATE INDEX idx_mls_soldDate ON Document (mls_soldDate);
CREATE INDEX idx_mls_status ON Document (mls_status);
